version: '3'
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 8081:80/tcp # http web interface
      - 3000:3000/tcp # initial setup web interface
    networks: 
      br0:
        ipv4_address: 192.168.114.4 #static address you want on the container
      bridge-net-0: 
        ipv4_address: 172.16.1.99
    environment: 
      TZ: 'Europe/Dublin'
    volumes: 
      - /mnt/user/docker/volumes/adguardhome/workdir:/opt/adguardhome/work
      - /mnt/user/docker/volumes/adguardhome/confdir:/opt/adguardhome/conf
    restart: always
  nginx-internal:
    container_name: nginx-internal
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - 80:80
      - 81:81
    environment:
      DISABLE_IPV6: 'true'
      DB_MYSQL_HOST:  "nginx-internal-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks: 
      br0:
        ipv4_address: 192.168.114.101
      bridge-net-0: {}
    volumes:
      - /mnt/user/docker/volumes/nginx-proxy-manager/data:/data
      - /usr/builtin/etc/certificate:/etc/ssl/certs
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    depends_on:
      - nginx-internal-db
  nginx-internal-db:
    container_name: nginx-internal-db
    restart: always
    image: mariadb:lts
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    networks: 
      bridge-net-0: {}
    volumes:
      - /mnt/user/docker/volumes/nginx-proxy-manager/database:/var/lib/mysql
    healthcheck:
      test: "healthcheck.sh --connect --innodb_initialized"
      interval: 10s
      timeout: 5s
      retries: 3
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 43200  # 12 hours (43200 seconds)
    restart: always
  # Commented out - using cloudflare tunnelling instead
  # nginx-external:
  #   container_name: nginx-external
  #   image: lscr.io/linuxserver/nginx:latest
  #   networks:
  #     bridge-net-0: {}
  #   ports:
  #     - 443:443
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /mnt/user/docker/volumes/nginx-external/config:/config
  #     - /usr/builtin/etc/certificate:/etc/ssl/certs:ro
  #     - /usr/builtin/etc/certificate:/config/keys:ro
  #   healthcheck:
  #     test: "curl -fk https://localhost:443"
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   restart: always

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    networks: 
      bridge-net-0: {}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 32680:80
    volumes:
      - /mnt/user/media/nextcloud/data:/data
      - /mnt/user/docker/volumes/nextcloud/config:/config
    healthcheck:
      test: 'occ status 2>/dev/null | grep -e "installed: true" -e "maintenance: false" -e "needsDbUpgrade: false" | wc -l | [ "`cat`" = "3" ]'
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    restart: always
    depends_on:
      - nextcloud-db
  
  nextcloud-db:
    image: mariadb:lts
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      bridge-net-0: {}
    volumes:
      - /mnt/user/docker/volumes/nextcloud/database:/var/lib/mysql
      - /mnt/user/docker/volumes/nextcloud/database/conf.d:/etc/mysql/conf.d
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=my-cool-bicycle
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=my-next-bicycle-cloud
    healthcheck:
      test: "healthcheck.sh --connect --innodb_initialized"
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: ["redis-server", "/data/redis.conf"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/docker/volumes/redis/data:/data
    networks:
      bridge-net-0: {}
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    network_mode: host
    environment:
      - WG_HOST=cooneyde.myasustor.com
      - WG_DEFAULT_DNS=192.168.114.1,1.1.1.1
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PORT=51820
    volumes:
      - /mnt/user/docker/volumes/wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp  # Web UI
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 8083:8080
    networks:
      bridge-net-0: {}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: "0:0"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: dashboard.home.com,192.168.114.2:3001
    ports:
      - 3001:3000
    volumes:
      - /mnt/appdata/docker/volumes/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: always
    networks:
      bridge-net-0: {}
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      bridge-net-0: {}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks: 
  br0:
    external: true
  bridge-net-0: 
    external: true