version: '3'
services: 
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server:latest
    restart: always
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.10
    environment: 
      WEBSOCKET_ENABLED: "true"
    ports:
      - 3012:3012
      - 80:80
    volumes:
      - /share/containers/volumes/bitwarden:/data  
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      VIRTUAL_HOST: "cooneyde.myqnapcloud.com"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.11
    volumes:
      - /share/containers/volumes/nginx-proxy-manager/data:/data
      - /share/containers/volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /share/containers/volumes/ssl-certs/ssl:/etc/ssl
    depends_on:
      - nginx-db
  nginx-db:
    container_name: nginx-db
    restart: always
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    networks: 
      docker-net-0: 
        ipv4_address: 192.168.114.12
    volumes:
      - /share/containers/volumes/mysql:/var/lib/mysql
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 6 * * *"
    restart: always
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BASE_URL=/ #optional
    volumes:
      - /share/containers/volumes/ombi:/config
    ports:
      - 3579:3579
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
networks: 
  docker-net-0:
    external: true
  docker-net-1:
    external: true