version: '3'
services: 
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    image: 'jc21/nginx-proxy-manager:2.9.22'
    ports:
      - '80:80'
      - '81:81'
      # - '443:443'
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: true
      # VIRTUAL_HOST: "cooneyde.myqnapcloud.com"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.11
    volumes:
      - /share/containers/volumes/nginx-proxy-manager/data:/data
      - /share/containers/volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      #- /share/containers/volumes/ssl:/etc/ssl
    depends_on:
      - nginx-db
  nginx-db:
    container_name: nginx-db
    restart: always
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    networks: 
      docker-net-0: 
        ipv4_address: 192.168.114.12
    volumes:
      - /share/containers/volumes/mysql:/var/lib/mysql
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 21600
    restart: always
networks: 
  docker-net-0:
    external: true
  docker-net-1:
    external: true