version: '3'
services: 
  nginx-proxy:
    container_name: nginxProxy
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - 8000:80
      - 8100:81
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: true
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.101
      bridge-net-0: {}
    volumes:
      - /volume1/Docker/volumes/nginx-proxy-manager/data:/data
      - /usr/builtin/etc/certificate:/etc/ssl/certs
      - /volume1/.@plugins/AppCentral/letsencrypt/.CertBot/config/live:/etc/letsencrypt

    depends_on:
      - nginx-db
  nginx-db:
    container_name: nginxDb
    restart: always
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    networks: 
      docker-net-0: 
        ipv4_address: 192.168.114.102
    volumes:
      - /volume1/Docker/volumes/mysql:/var/lib/mysql
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 21600
    restart: always
  npm-external:
    container_name: npmExternal
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - 8081:80
      - 443:443
      - 8181:81
    environment:
      CURL_CA_BUNDLE: "/etc/ssl/certs/ssl.crt"
      SSL_CERT_FILE: "/etc/ssl/certs/ssl.crt"
      DB_MYSQL_HOST: "127.0.0.1"
      DB_MYSQL_PORT: 3366
      DB_MYSQL_USER: "npm_ext"
      DB_MYSQL_PASSWORD: "npm_ext_pass"
      DB_MYSQL_NAME: "npm_external"
      DISABLE_IPV6: true
    # network_mode: host
    # networks:
    #   docker-net-0:
    #     ipv4_address: 192.168.114.125
    #   bridge-net-0: {}
    volumes:
      - /volume1/Docker/volumes/npm-external/data:/data
      - /usr/builtin/etc/certificate:/etc/ssl/certs
      - /usr/builtin/etc/certificate:/custom_certs:ro
      - /volume1/Docker/volumes/npm-external/letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-external-db
  npm-external-db:
    container_name: npmExternalDb
    restart: always
    image: 'jc21/mariadb-aria:latest'
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'npm_ext_root_pass'
      MYSQL_DATABASE: 'npm_external'
      MYSQL_USER: 'npm_ext'
      MYSQL_PASSWORD: 'npm_ext_pass'
    # networks:
    #   bridge-net-0: {}
    volumes:
      - /volume1/Docker/volumes/npm-external/mysql:/var/lib/mysql

  nginx-external:
    container_name: nginx-external
    restart: always
    image: lscr.io/linuxserver/nginx:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/Docker/volumes/nginx-external/config:/config
      - /usr/builtin/etc/certificate:/etc/ssl/certs
    ports:
      - 80:80
      - 443:443
  
  # nextcloud:
  #   image: nextcloud
  #   container_name: nextcloud
  #   networks: 
  #     docker-net-0: 
  #       ipv4_address: 192.168.114.16
  #   volumes:
  #     - /share/containers/volumes/nextcloud/data:/var/www/html
  #   restart: always
  #   depends_on:
  #     - nextcloud-db
  
  # nextcloud-db:
  #   image: mariadb
  #   container_name: nextcloud-db
  #   command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   volumes:
  #     - /share/containers/volumes/nextcloud/database:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=my-cool-bicycle
  #     - MYSQL_DATABASE=nextcloud
  #     - MYSQL_USER=nextcloud
  #     - MYSQL_PASSWORD=my-next-bicycle-cloud
  #   restart: always
networks: 
  docker-net-0:
    external: true
  docker-net-1:
    external: true
  bridge-net-0: 
    external: true