version: '3'
services: 
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: true
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.101
    volumes:
      - /volume1/Docker/volumes/nginx-proxy-manager/data:/data
      - /volume1/Docker/volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /volume1/.@plugins/AppCentral/letsencrypt/.CertBot/config/live:/etc/ssl
    depends_on:
      - nginx-db
  nginx-db:
    container_name: nginx-db
    restart: always
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    networks: 
      docker-net-0: 
        ipv4_address: 192.168.114.102
    volumes:
      - /volume1/Docker/volumes/mysql:/var/lib/mysql
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 21600
    restart: always
  # nextcloud:
  #   image: nextcloud
  #   container_name: nextcloud
  #   networks: 
  #     docker-net-0: 
  #       ipv4_address: 192.168.114.16
  #   volumes:
  #     - /share/containers/volumes/nextcloud/data:/var/www/html
  #   restart: always
  #   depends_on:
  #     - nextcloud-db
  
  # nextcloud-db:
  #   image: mariadb
  #   container_name: nextcloud-db
  #   command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   volumes:
  #     - /share/containers/volumes/nextcloud/database:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=my-cool-bicycle
  #     - MYSQL_DATABASE=nextcloud
  #     - MYSQL_USER=nextcloud
  #     - MYSQL_PASSWORD=my-next-bicycle-cloud
  #   restart: always
networks: 
  docker-net-0:
    external: true
  docker-net-1:
    external: true