version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee
    restart: always
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks: 
      bridge-net-0: {}
    ports:
      - 9000:9000
    entrypoint: /portainer -p :9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/Docker/volumes/portainer:/data
    healthcheck:
      test: ["CMD", "/portainer", "--healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
  monitoring:
    image: nicolargo/glances:ubuntu-latest-full
    container_name: monitoring
    pid: host
    # network_mode: host
    ports:
      - 61208:61208
    networks:
      bridge-net-0: {}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
networks: 
  bridge-net-0:
    external: true