version: "3"
services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - deluge
      - jackett
      - ombi
      - plex
      - portainer
      - radarr
      - sonarr
    command: 
      - "watchtower --interval 21600"
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - /share/cachedev1/ombi:/config
    ports:
      - 3579:3579
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
networks: 
  docker-net-0:
    external: true
  docker-net-1:
    external: true