version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.5
    ports:
      - 80:9000
    entrypoint: /portainer -p :80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/cachedev1/portainer:/data  
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - /share/cachedev1/ombi:/config
    ports:
      - 3579:3579
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
networks: 
  docker-net-0:
    external: true
  docker-net-1:
    external: true