version: "3.8"
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /volume1/Docker/volumes/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    dns:
      - 127.0.0.1
      - 1.1.1.1      
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.13
networks: 
  docker-net-0:
    external: true