services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 8123:8123
    volumes:
      - /mnt/appdata/docker/volumes/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /usr/builtin/etc/certificate:/etc/ssl/certs
    privileged: true
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    network_mode: host
    # networks: 
    #   bridge-net-0:
    #     ipv4_address: 172.16.1.10

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - /mnt/appdata/docker/volumes/matter-server:/data
      - /run/dbus:/run/dbus:ro
    privileged: true 
    networks: 
      bridge-net-0:
        ipv4_address: 172.16.1.11
networks: 
  bridge-net-0:
    external: true
