version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.3.2 # 
    container_name: mealie
    networks: 
      docker-net-0-test:
        ipv4_address: 192.168.114.19
    depends_on:
      - postgres-mealie
    volumes:
      - /share/containers/volumes/mealie/data/:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1

    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=postgres-mealie
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: always
  postgres-mealie:
    container_name: postgres-mealie
    image: postgres:15
    restart: always
    volumes:
      - /share/containers/volumes/mealie/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
networks: 
  docker-net-0-test:
    external: true
volumes:
  mealie-data:
    driver: local
  mealie-pgdata:
    driver: local