version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: cooneyde
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.6
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - VERSION=docker
    volumes:
      - /volume1/Docker/volumes/plex:/config
      - /volume1/Video/tv-shows:/tv
      - /volume1/Video/Movies:/movies
      - /volume1/Video/transcode:/transcode
    restart: always
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/identity"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /volume1/Docker/volumes/radarr:/config
      - /volume1/Video/Movies:/movies
      - /volume1/Download:/downloads
    ports:
      - 7878:7878
    restart: always
    depends_on:
      - jackett
      - deluge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.106
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - VERSION=docker
      - TZ=Europe/London
    ports:
      - 8989:8989
    volumes:
      - /volume1/Docker/volumes/sonarr:/config
      - /volume1/Video/tv-shows:/tv
      - /volume1/Download:/downloads
    restart: always
    depends_on:
      - jackett
      - deluge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.107
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /volume1/Docker/volumes/overseerr/config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.108
    restart: always
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /volume1/Docker/volumes/deluge:/config
      - /volume1/Download:/downloads
    ports:
      - 8112:8112
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8112"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.109
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /volume1/Docker/volumes/jackett:/config
      - /volume1/Download:/downloads
    ports:
      - 9117:9117
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9117"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.110
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      -  /volume1/Docker/volume/sprowlarr/data:/config
    restart: always
    ports:
      - 9696:9696
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.111
networks: 
  docker-net-0:
    external: true