version: '3'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: cooneyde
    networks: 
      docker-net-1:
        ipv4_address: 192.168.114.6
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /share/containers/volumes/plex:/config
      - /share/Multimedia/video/tv-shows:/tv
      - /share/Multimedia/video/Movies:/movies
      - /share/Multimedia/transcode:/transcode
    restart: always
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/identity"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /share/containers/volumes/radarr:/config
      - /share/Multimedia/video/Movies:/movies
      - /share/Download:/downloads
    ports:
      - 7878:7878
    restart: always
    depends_on:
      - jackett
      - deluge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-1:
        ipv4_address: 192.168.114.7
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 8989:8989
    volumes:
      - /share/containers/volumes/sonarr:/config
      - /share/Multimedia/video/tv-shows:/tv
      - /share/Download:/downloads
    restart: always
    depends_on:
      - jackett
      - deluge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-1:
        ipv4_address: 192.168.114.8
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /share/containers/volumes/deluge:/config
      - /share/Download:/downloads
    ports:
      - 8112:8112
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8112"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-0:
        ipv4_address: 192.168.114.15
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /share/containers/volumes/jackett:/config
      - /share/Download:/downloads
    ports:
      - 9117:9117
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9117"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks: 
      docker-net-1:
        ipv4_address: 192.168.114.9
networks: 
  docker-net-0:
    external: true
  docker-net-1:
    external: true